//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoAppPackageMaker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoAppPackageMaker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binary architecture of the contents of the package. It is not permitted to have multiple binary architectures in the same package..
        /// </summary>
        internal static string PackageArchitecture {
            get {
                return ResourceManager.GetString("PackageArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cosmetic name for the product being packaged..
        /// </summary>
        internal static string PackageDisplayName {
            get {
                return ResourceManager.GetString("PackageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more URLs of feed locations that may be consulted when looking for a package upgrade..
        /// </summary>
        internal static string PackageFeed {
            get {
                return ResourceManager.GetString("PackageFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more URLs that will return the package file. The URL must not be a referencing webpage, as this is the URL that the package manager will attempt to fetch the package from directly..
        /// </summary>
        internal static string PackageLocation {
            get {
                return ResourceManager.GetString("PackageLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full name of the package, without any version, platform or public key information..
        /// </summary>
        internal static string PackageName {
            get {
                return ResourceManager.GetString("PackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An identity-reference that contains the name, email and web address of the person or organization that created this package. This is not necessarily the author, of which should be listed in the metadata/contributors property..
        /// </summary>
        internal static string PackagePublisher {
            get {
                return ResourceManager.GetString("PackagePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The four-digit-version of the package. (ie, 1.2.3.4).
        /// </summary>
        internal static string PackageVersion {
            get {
                return ResourceManager.GetString("PackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package rule contains the manditory data for creating a package..
        /// </summary>
        internal static string TabPackage {
            get {
                return ResourceManager.GetString("TabPackage", resourceCulture);
            }
        }
    }
}
